### ISSUE TITLE
Connection to a docker container polkadot node 

### ISSUE THREAD

**Issue by HikaruG** [SimplyVC/polkadot_api_server#20]
### Trying to connect the the ws of my polkadot container 
Hi, I am finding difficulties reaching my docker node using the ws_url. 
Is it possible to have some assistance from your side? 

So far, I have tried: 

- the classic port-fowarding: the node container (let's call it container A) with -p9944:9944 option. however, this fails as the localhost of the polkadot_api_server's container localhost is not the same as my host's. 
- the socat brigde: a socat container using the --network=container:containerA. Not much success either 
Unfortunately, my host pc is a Mac, therefore I cannot use the --network=host option on docker. 

The value for the ws url is always: wss://localhost:9944

Is there any ways I can make this work? Thank you very much for your help.

**Comment by HikaruG** [comment]
Sorry misstyped and pressed enter, I am modifying it still. I am terrible sorry

**Comment by dillu24** [comment]
Hi @HikaruG , thanks for your question.

If your node is running in a docker container on host `1.1.1.1.1`, you must enter `ws://1.1.1.1.1:9944` in the API Server configuration. Note, you need to write `ws` and not `wss`. Also, make sure that port 9944 is accessible from the outside.

Let me know if you need further assistance.

**Comment by HikaruG** [comment]
> Hi @HikaruG , thanks for your question.
> 
> If your node is running in a docker container on host `1.1.1.1.1`, you must enter `ws://1.1.1.1.1:9944` in the API Server configuration. It is not a problem for the API server to connect with nodes running on different hosts.
> 
> Note, you need to write `ws` and not `wss`. Also, make sure that port 9944 is accessible from the outside.
> 
> Let me know if you need further assistance.

Thank you so much for your prompt answer @dillu24 !
I was able to make it work using the --ws-unsafe-external option on my node side, and using the local ip of my host for the api.
